spring:
  datasource:
    url: jdbc:postgresql://${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    platform: postgresql
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT:5672}
    listener:
      simple:
        prefetch: 1
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
api:
  queueName: ${QUEUE_NAME}
